// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASktSUHUkqdKCVd6r5hof9CMcuaeYQ2VM',
    appId: '1:726980329071:web:c9e7e815c11ccc63ec179a',
    messagingSenderId: '726980329071',
    projectId: 'mychat-969fd',
    authDomain: 'mychat-969fd.firebaseapp.com',
    storageBucket: 'mychat-969fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2Gbsm-tyKSJoETlXgAOBTf171QSthWc',
    appId: '1:726980329071:android:a79260e170fc8052ec179a',
    messagingSenderId: '726980329071',
    projectId: 'mychat-969fd',
    storageBucket: 'mychat-969fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRobOvuWt5wlOzb97YW31UjfHiBO8wk1A',
    appId: '1:726980329071:ios:f60a561a40a3d650ec179a',
    messagingSenderId: '726980329071',
    projectId: 'mychat-969fd',
    storageBucket: 'mychat-969fd.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRobOvuWt5wlOzb97YW31UjfHiBO8wk1A',
    appId: '1:726980329071:ios:f60a561a40a3d650ec179a',
    messagingSenderId: '726980329071',
    projectId: 'mychat-969fd',
    storageBucket: 'mychat-969fd.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASktSUHUkqdKCVd6r5hof9CMcuaeYQ2VM',
    appId: '1:726980329071:web:8e149a3bd3b083d4ec179a',
    messagingSenderId: '726980329071',
    projectId: 'mychat-969fd',
    authDomain: 'mychat-969fd.firebaseapp.com',
    storageBucket: 'mychat-969fd.appspot.com',
  );
}
